language: java
script:
- npm run ci
- chmod 777 src/test/run_tests.sh
- src/test/run_tests.sh
before_script:
- python -m SimpleHTTPServer &

env:
  global:
    secure: SpAoWhmw96wpcM2udrxGHv+Ee8vjzBBFmUbv4DBkjwpHmpytEaViJDI+WpeY0kUsZo8S5z69wAvHptdnJu4ABwRfU3CGOnGq2pdJCB63DQf1ofv4OcpseCviMtZUCfqL+QrrvZciP3kkrgyoEJ//Fib6k49tvptFTNLZmCLM9iIJ7X/JLkaByjTIyD6lF37umh08xefeVQoopubdQRI5VcWIZsIkUQPGtstJan9nqwqDEajvC6zzGS7SVrRfCldbMLhcPqE5lXoMJppckoIgDmEjj9innc29TMglz4ds5gdWYOIOG+SQEIP1Kpgmg8/ftObYYC/pJZXI9J8sv2GEBejpunO0dnnMaitoJbNzlRKI8HQhoq50FZV7cp2wtNasUeF8YvtIdQb7H3SuBNsqD0xWMh5MS6G85EWglxk8C9lhAvgnZ7tobR2WrsmTbI8/8ijcutX84QFk/OZfx9IKz9sw1Ai3vUN/lTLc5BPFi+1ZyRYwrXOox/8up+6oo4WVt0YmyToDW05E5owkb/wPHlb/k9QQPhXdUOwYTvxK7JrBBHPOHg+HhsEDCr5jaF21VwD1e/fCHY94z/BtjK/v7d3bDQ6hRESk8sXdHkZVM2K9PkVZXfhDcJSUTY07/ED5FwP30UrZl27XjD+nqSxBVpaFMzSjTjFo/lTh57dKit4=
